### ISSUE TITLE
Sonoff T1 2 Gang

### ISSUE THREAD

**Issue by Pi198** [jp112sdl/SonoffDualShutterHMLOX#4]
Hallo. 
Erstmal vielen Dank für die geile Firmware. Ist es auch möglich diese Firmware auf einem Sonoff T1 2Gang zu installieren? 

Vielen Dank für deine Antwort

Gruß Sebastian

**Comment by jp112sdl** [comment]
Hi.
Ich habe nie einen T1 2 Gang in der Hand gehabt... keine Ahnung, ob das mit den GPIO Pins und Relais so passt. 
Ich denke aber eher nicht.

VG,
Jérôme

**Comment by Pi198** [comment]
Hi. Erstmal vielen Dank für deine schnelle Antwort. Ja dann muss ich mal
schauen ob ich das doch noch hinbekomme.  Habe mit programmieren nicht viel
am Hut. Bin gelernter Elektriker.


Mfg Sebastian Schiemann

Jérôme <notifications@github.com> schrieb am Sa., 11. Aug. 2018, 20:49:

**Comment by Pi198** [comment]
Hi. Ist es denn viel Aufwand den t1 2gang einzupflegen? Ich denke mal das würden einige User toll finden. Ich bin kein Programmierer deswegen kenne ich den Aufwand nicht. Als leihe würde ich sagen, das man aus der tasmota firmware die Infos bekommt die man brauch. Oder sehe ich das falsch. Wenn ich dir irgendwie helfen kann, dann sag es mir. Ich versuche mein bestes. 

Mfg Sebastian

**Comment by jp112sdl** [comment]
> Ich denke mal das würden einige User toll finden.

Bis jetzt bist du nach fast 1 Jahr der erste, der danach fragt. 😄 

>  Ich bin kein Programmierer deswegen kenne ich den Aufwand nicht. 

Ja, das ist leider oftmals das Problem. Von außen sieht es immer nach "kann so schwer nicht sein" aus.

> Als leihe würde ich sagen, das man aus der tasmota firmware die Infos bekommt die man brauch. 

Ich kenne Tasmota nicht und habe auch keine Zeit / Motivation, mich durch unbekannte Sourcecodes zu wühlen.
Wenn du mir sagen kannst, welche GPIO Pins für die Taster 1 und 2 sowie Relais 1 und 2 verwendet werden, dann brauchst du sie nur [hier](https://github.com/jp112sdl/SonoffDualShutterHMLOX/blob/c0f15e827ccf4f84df16e34dde202add3c844cae/SonoffDualShutterHMLOX.ino#L38) ändern.

_Sofern aber ein serieller Logikbaustein verwendet wird (wie es beim Dual [nicht R2]) der Fall ist, können wir an der Stelle abbrechen._

**Comment by Pi198** [comment]
Guten Morgen Jérôme,

 

Nochmals vielen Dank für deine Antwort. Ich habe nun mal in der Tasmota Firmware gesucht und habe folgendes gefunden:

 

  { "Sonoff Dual R2",  // Sonoff Dual R2 (ESP8285)

     GPIO_USER,        // GPIO00 Button 0 on header (0 = On, 1 = Off)

     GPIO_USER,        // GPIO01 Serial RXD and Optional sensor

     0,

     GPIO_USER,        // GPIO03 Serial TXD and Optional sensor

     0,

     GPIO_REL2,        // GPIO05 Relay 2 (0 = Off, 1 = On)

     0, 0, 0,          // Flash connection

     GPIO_USER,        // GPIO09 Button 1 on header (0 = On, 1 = Off)

     GPIO_KEY1,        // GPIO10 Button on casing

     0,                // Flash connection

     GPIO_REL1,        // GPIO12 Relay 1 (0 = Off, 1 = On)

     GPIO_LED1_INV,    // GPIO13 Blue Led (0 = On, 1 = Off)

     0, 0, 0, 0

  },

 

  { "Sonoff T1 2CH",   // Sonoff T1 2CH (ESP8285)

     GPIO_KEY1,        // GPIO00 Button 1

     GPIO_USER,        // GPIO01 Serial RXD and Optional sensor

     GPIO_USER,        // GPIO02 Optional Sensor (J3 Pin 5)

     GPIO_USER,        // GPIO03 Serial TXD and Optional sensor

     0,

     GPIO_REL2,        // GPIO05 Blue Led and Relay 2 (0 = Off, 1 = On)

     0, 0, 0,          // Flash connection

     GPIO_KEY2,        // GPIO09 Button 2

     0,

     0,                // Flash connection

     GPIO_REL1,        // GPIO12 Blue Led and Relay 1 (0 = Off, 1 = On)

     GPIO_LED1_INV,    // GPIO13 Blue Led (0 = On, 1 = Off)

     0, 0, 0, 0

  },

 

Da die meisten GPIO übereinstimmen habe ich mal deine Firmware aufgespielt. Leider hat das nicht funktioniert. 

Die Weboberfläche funktioniert aber die Relays werden nicht geschaltet und auch die Touchbutton zeigen keine Reaktion. Wenn ich die Tasmota auf Dual R2 umstelle, dann kann ich ber die Weboberfläche den T1 schalten, aber nicht über die touchbutton. Was macht GPIO10 in deiner Firmware? Der ist beim T1 nicht beschrieben. Beim T2 3gang ist er für den Button3. 

 

Ich hoffe du kannst mir noch einen Tipp geben. 

 

Vielen Dank

 

Sebastian

 

 

 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by jp112sdl** [comment]
> Was macht GPIO10 in deiner Firmware?

Ist bei Tasmota:
`GPIO_KEY1, // GPIO10 Button on casing`
und bei meiner FW dafür vorgesehen, den Konfigurationsmodus (AP-Mode) zu aktivieren.

Laut deinen Angaben zum T2 müsste es eigentlich funktionieren. 
Die Pin Nummern der Buttons und Relais sind identisch mit dem Dual R2.

Kommst du denn mit meiner Firmware überhaupt in den AP-Mode?
So lange noch keine gespeicherte Konfiguration existiert, passiert das automatisch. 
Aber sonst müsstest du eigentlich einen anderen Pin definieren:

[SonoffDualShutterHMLOX.ino#L180](
https://github.com/jp112sdl/SonoffDualShutterHMLOX/blob/988e459e82ff9f237575e0a94fdfb95aa5d8b8bd/SonoffDualShutterHMLOX.ino#L180) z.B.
`digitalRead(SwitchPinHeadDualR2) == LOW` -> `digitalRead(Switch2PinDualR2) == LOW`

**Comment by Pi198** [comment]
Ich hatte aus der tasmota firmware über die updatefunktion deine firmware
eingespielt. Danach hat mir der Browser das konfigurationsportal angezeigt.
( er zeigte mir das allerdings unter der alten ip Adresse von der tasmota
firmware) Da habe ich dann die W-lan einstellungen, die ip der ccu, den
sonoff Gerätenamen und das Backend eingestellt. Danach könnte ich unter
Konfiguration noch die Einstellungen vornehmen. Ich glaube aber das es ein
Fehler war die firmware über die updatefunktion einzuspielen. Ich werde es
nochmal versuchen direkt über den esploader zu flashen.

Dann bin ich mal gespannt ob er die touch Button auch erkennt. Wenn ich die
tasmota auf den dual r2 umstelle dann funktionieren diese nicht.

Achso mal was zum Hintergrund. Meine Idee war es den t1 2gang als
schalterersatz in der UP Dose zu nehmen, damit ich meinen schwer zu
erreichenden rolladenkasten nicht öffnen muss. So brauche ich auch nur 1
Trennrelais wegen dem interlock und nicht noch ein zweites um einen taster
am sonoff anzuschließen.

Mfg Sebastian

Jérôme <notifications@github.com> schrieb am Mi., 22. Aug. 2018, 10:50:

**Comment by Pi198** [comment]
Nachtrag.

So bin ich in den ap Modus nicht gekommen. Nur nach dem flashen.

Wie gesagt ich probiere es nochmal und Berichte dann.

Jérôme <notifications@github.com> schrieb am Mi., 22. Aug. 2018, 10:50:

**Comment by Pi198** [comment]
Guten Morgen Jérôme,

 

So hier hast du meinen Bericht:

 

Ich habe heute nochmal deine Firmware auf dem T1  2Gang geflasht und siehe da es funktioniert. Ich kann den Sonoff über die Touchflächen, die Weboberfläche und über die HM CCU bedienen. Hoch, Runter, Stop, fahre zu wert ist kein Problem. Genau so wie es beim Dual R2 funktioniert.

 

Was habe ich gemacht:

Sonoff geöffnet

Oberste Platine entfernt

FTDI Adapter angeschlossen und mit USB verbunden

ESP Loader gestartet und deine Firmware ausgewählt

Resettaster auf der Platine 7x schnell hintereinander gedrückt

Im ESP Loader auf Flash gedrückt (Manchmal funktioniert es nicht sofort, dann nochmal versuchen)

Nach dem Flashen startet der Sonoff neu und der Shutter AP erscheint

Mit Shutter AP verbunden und W-lan, IP der CUU eingestellt. Als Gerät den Dual R2 ausgewählt

Gespeichert und in der Fritzbox die IP rausgesucht

Ab jetzt alles nach deiner Anleitung

 

Ich habe nur noch nicht rausgefunden wie ich wieder in den Konfigurationsmodus komme, da die LED nicht 4sec lang schnell blinkt. Über die http Steuerbefehle funktioniert es aber nicht am Sonoff selber. 

 

Ich danke dir für deine Unterstützung und hoffe das auch andere die neuen Erkenntnisse gebrauchen können. So kann man den T1 2Gang (in Verbindung mit einem Trennrelais) super als Rolladenaktor nutzen.

 

Vielen Dank

 

Sebastian



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by jp112sdl** [comment]
> Ich habe nur noch nicht rausgefunden wie ich wieder in den Konfigurationsmodus komme, da die LED nicht 4sec lang schnell blinkt.

Hattest du den Code angepasst, wie im vorherigen [Kommentar](
https://github.com/jp112sdl/SonoffDualShutterHMLOX/issues/4#issuecomment-414960669)?

**Comment by Pi198** [comment]
Stimmt hatte ich vergessen. Werde ich noch nachholen. Dann müsste es ja klappen.

**Comment by Pi198** [comment]
Hallo Jerome,

Auch ich hatte in letzter Zeit wenig Zeit für mein smarthome. Ja den Code
hatte ich angepasst, hat auch soweit funktioniert.

Leider habe ich ein neues Phänomen.
Ich habe einen neuen Router bekommen und bin mit meinem smarthome von einer
fritzbox 7490 auf eine 7590 umgezogen. Hat auch alles super geklappt bis
auf die rollosteuerung ( einmal einen dual r2 und einmal den t1 2gang).

Wenn ich im konfigurationsportal die neuen W-lan Daten eintrage, werden
diese nicht gespeichert. Er verbindet sich weiterhin mit der 7490, aber
nicht mit der 7590. Ich habe auch mal drüber gefälscht, den sonoff komplett
gelöscht. Jedes mal wenn ich die Daten von der 7590 eingebe, verbindet er
sich mit den alten daten der 7490. Ssid und passwort sind natürlich neu.
Hast du eine idee was ich noch machen kann?

Ich danke dir schon mal.


Sebastian

Jérôme <notifications@github.com> schrieb am Do., 23. Aug. 2018, 15:33:

**Comment by jp112sdl** [comment]
Hi.
So richtig habe ich da keine Idee.
Du könntest mal seriell mitloggen, was beim Speichern der Konfiguration ausgegeben wird.

Ist evtl. im WLAN Passwort ein "komisches" Sonderzeichen drin?
Das wird per HTTP GET übergeben. Nich dass da irgendwas auf der Strecke bleibt.

**Comment by Pi198** [comment]
Guten Morgen,

In der Ssid ist ein ! Vorhanden sonst nur Buchstaben und Zahlen. Im
passwort sind nur zahlen. Die alten w-lan Daten sind genau so aufgebaut.
Wenn ich den seriellen Monitor vom arduino IDE mitlaufen lasse kommen
komische Zeichen in der Ausgabe nach dem Neustart.

Genutzt habe ich deine fertige Datei.

Ich werde nochmal ein wenig rumprobieren.

Nochmal vielen Dank.

Sebastian

Jérôme <notifications@github.com> schrieb am Di., 25. Sep. 2018, 21:15:

**Comment by jp112sdl** [comment]
> Wenn ich den seriellen Monitor vom arduino IDE mitlaufen lasse kommen
komische Zeichen in der Ausgabe nach dem Neustart.

Hast du 115200 Baud eingestellt?
